module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "alice-blue": "var(--alice-blue)",
        beeswax: "var(--beeswax)",
        black: "var(--black)",
        "black-50": "var(--black-50)",
        buttercup: "var(--buttercup)",
        "catskill-white": "var(--catskill-white)",
        "dodger-blue": "var(--dodger-blue)",
        ebony: "var(--ebony)",
        fiord: "var(--fiord)",
        flamingo: "var(--flamingo)",
        "gull-gray": "var(--gull-gray)",
        korma: "var(--korma)",
        mystic: "var(--mystic)",
        "pattens-blue": "var(--pattens-blue)",
        "persian-blue": "var(--persian-blue)",
        "royal-blue": "var(--royal-blue)",
        "slate-gray": "var(--slate-gray)",
        "sweet-corn": "var(--sweet-corn)",
        white: "var(--white)",
        "white-20": "var(--white-20)",
        "white-95": "var(--white-95)",
        "white-catskill-white": "var(--white-catskill-white)",
        zumthor: "var(--zumthor)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "arial-bold": "var(--arial-bold-font-family)",
        "inter-medium": "var(--inter-medium-font-family)",
        "inter-regular": "var(--inter-regular-font-family)",
        "inter-semi-bold": "var(--inter-semi-bold-font-family)",
        "inter-semi-bold-upper": "var(--inter-semi-bold-upper-font-family)",
        "semantic-button": "var(--semantic-button-font-family)",
        "semantic-heading-1": "var(--semantic-heading-1-font-family)",
        "semantic-heading-2": "var(--semantic-heading-2-font-family)",
        "semantic-input": "var(--semantic-input-font-family)",
        "semantic-label": "var(--semantic-label-font-family)",
        "semantic-options": "var(--semantic-options-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [require("tailwindcss-animate")],
  darkMode: ["class"],
};
